// ==========================================================================
// VERIFICATION SUBMISSION - Graph/Flow_And_Matching/Bipartite_Matching_Hopcroft_Karp.cpp
//
// Target: https://judge.yosupo.jp/problem/bipartitematching
//
// The block between the markers is the template copied byte for byte. Only the
// driver below it was added, to match this judge's input format.
// Generated by tools/verify.py - do not edit by hand.
// ==========================================================================

// ---------------- BEGIN VERBATIM COPY OF Graph/Flow_And_Matching/Bipartite_Matching_Hopcroft_Karp.cpp ----------
// Bipartite Matching Hopcroft Karp: the same matching as Kuhn, but augmenting many shortest paths at once.
// Use when: the bipartite graph is large enough that O(V * E) is too slow - tens of thousands of nodes and edges.
// Handles: unequal side sizes, unmatched nodes, multi-edges, isolated nodes. Bipartite graphs only.
// Time: O(E * sqrt(V))
// Indexing: 1-based on both sides, left 1..n and right 1..m, numbered independently
// Note: same answer as Bipartite_Matching.cpp, which is shorter to type. Reach for this only when the size demands it.

#include <bits/stdc++.h>
using namespace std;

struct Hopcroft_Karp {
    static const int INF = INT_MAX;

    int n, m;
    vector<vector<int>> adj;
    vector<int> match_left, match_right, dist; // 0 means unmatched

    Hopcroft_Karp(int n, int m)
        : n(n), m(m), adj(n + 1), match_left(n + 1, 0), match_right(m + 1, 0), dist(n + 1, 0) {}

    void add_edge(int u, int v) { adj[u].push_back(v); } // left u, right v

    bool bfs() { // layer the graph; false when no augmenting path remains
        queue<int> q;
        bool found = false;
        for (int u = 1; u <= n; u++) {
            if (!match_left[u])
                dist[u] = 0, q.push(u);
            else
                dist[u] = INF;
        }
        while (!q.empty()) {
            int u = q.front();
            q.pop();
            for (int v : adj[u]) {
                int back = match_right[v];
                if (!back)
                    found = true; // reached a free right node, so an augmenting path exists
                else if (dist[back] == INF) {
                    dist[back] = dist[u] + 1;
                    q.push(back);
                }
            }
        }
        return found;
    }

    bool dfs(int u) {
        for (int v : adj[u]) {
            int back = match_right[v];
            if (!back || (dist[back] == dist[u] + 1 && dfs(back))) {
                match_left[u] = v;
                match_right[v] = u;
                return true;
            }
        }
        dist[u] = INF;
        return false;
    }

    int maximum_matching() { // also fills match_left and match_right
        fill(match_left.begin(), match_left.end(), 0);
        fill(match_right.begin(), match_right.end(), 0);
        int total = 0;
        while (bfs())
            for (int u = 1; u <= n; u++)
                if (!match_left[u] && dfs(u)) total++;
        return total;
    }

    vector<pair<int, int>> pairs() { // the matched (left, right) pairs
        vector<pair<int, int>> out;
        for (int u = 1; u <= n; u++)
            if (match_left[u]) out.push_back({u, match_left[u]});
        return out;
    }
};

// Standard problem: n left nodes, m right nodes, k allowed pairs - report the matching size and the pairs
void solve() {
    int n, m, k;
    cin >> n >> m >> k;
    Hopcroft_Karp hk(n, m);
    for (int i = 0, u, v; i < k; i++) {
        cin >> u >> v;
        hk.add_edge(u, v);
    }
    cout << hk.maximum_matching() << '\n';
    for (auto [u, v] : hk.pairs()) cout << u << ' ' << v << '\n';
}
// ---------------- END VERBATIM COPY ----------------------------------------

// Driver only. The template is 1-based on both sides; the judge is 0-based.
int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(nullptr);
    int l, r, m;
    cin >> l >> r >> m;
    Hopcroft_Karp bm(l, r);
    for (int i = 0, a, b; i < m; i++) {
        cin >> a >> b;
        bm.add_edge(a + 1, b + 1);
    }
    string out = to_string(bm.maximum_matching()) + "\n";
    for (auto [u, v] : bm.pairs()) out += to_string(u - 1) + " " + to_string(v - 1) + "\n";
    cout << out;
}
