// ==========================================================================
// VERIFICATION SUBMISSION - Math/Polynomial/NTT.cpp
//
// Target: https://judge.yosupo.jp/problem/convolution_mod
//
// The block between the markers is the template copied byte for byte. Only the
// driver below it was added, to match this judge's input format.
// Generated by tools/verify.py - do not edit by hand.
// ==========================================================================

// ---------------- BEGIN VERBATIM COPY OF Math/Polynomial/NTT.cpp ----------
// NTT: exact polynomial multiplication modulo an NTT-friendly prime, with integer arithmetic only.
// Use when: the answer is wanted mod 998244353, or coefficients are too large for FFT's doubles to stay exact.
// Handles: any lengths, empty inputs, negative coefficients, and polynomial power via repeated squaring.
// Time: O(n log n)
// Indexing: 0-based; result[k] is the sum of a[i] * b[j] over i + j == k, of length a.size() + b.size() - 1
// Note: the padded length must divide 2^23 here, so up to 8.3e6 terms. For another modulus use NTT_Any_Mod.cpp.

#include <bits/stdc++.h>
using namespace std;
using ll = long long;

const ll NTT_MOD = 998244353; // 119 * 2^23 + 1
const ll NTT_ROOT = 3;        // a primitive root of NTT_MOD

ll pow_mod(ll b, ll e, ll m) {
    ll r = 1 % m;
    b %= m;
    if (b < 0) b += m;
    while (e > 0) {
        if (e & 1) r = r * b % m;
        b = b * b % m;
        e >>= 1;
    }
    return r;
}

// a primitive root of a prime p, for when you want an NTT under some other friendly prime
ll primitive_root(ll p) {
    vector<ll> factors;
    ll phi = p - 1, m = phi;
    for (ll f = 2; f * f <= m; f++)
        if (m % f == 0) {
            factors.push_back(f);
            while (m % f == 0) m /= f;
        }
    if (m > 1) factors.push_back(m);
    for (ll g = 2; g <= p; g++) {
        bool ok = true;
        for (ll f : factors)
            if (pow_mod(g, phi / f, p) == 1) { ok = false; break; }
        if (ok) return g;
    }
    return -1;
}

void ntt(vector<ll> &a, bool invert, ll mod = NTT_MOD, ll root = NTT_ROOT) {
    int n = (int)a.size();
    for (int i = 1, j = 0; i < n; i++) {
        int bit = n >> 1;
        for (; j & bit; bit >>= 1) j ^= bit;
        j ^= bit;
        if (i < j) swap(a[i], a[j]);
    }
    for (int len = 2; len <= n; len <<= 1) {
        ll w = pow_mod(root, (mod - 1) / len, mod);
        if (invert) w = pow_mod(w, mod - 2, mod);
        for (int i = 0; i < n; i += len) {
            ll cur = 1;
            for (int j = 0; j < len / 2; j++) {
                ll u = a[i + j], v = a[i + j + len / 2] * cur % mod;
                a[i + j] = (u + v) % mod;
                a[i + j + len / 2] = (u - v + mod) % mod;
                cur = cur * w % mod;
            }
        }
    }
    if (invert) {
        ll inv_n = pow_mod(n, mod - 2, mod);
        for (ll &x : a) x = x * inv_n % mod;
    }
}

vector<ll> multiply(vector<ll> a, vector<ll> b, ll mod = NTT_MOD, ll root = NTT_ROOT) {
    if (a.empty() || b.empty()) return {};
    int need = (int)(a.size() + b.size() - 1), n = 1;
    while (n < need) n <<= 1;
    for (ll &x : a) x = ((x % mod) + mod) % mod;
    for (ll &x : b) x = ((x % mod) + mod) % mod;
    a.resize(n), b.resize(n);
    ntt(a, false, mod, root), ntt(b, false, mod, root);
    for (int i = 0; i < n; i++) a[i] = a[i] * b[i] % mod;
    ntt(a, true, mod, root);
    a.resize(need);
    return a;
}

// a raised to the power e, truncated to keep_length terms (0 keeps everything)
vector<ll> poly_pow(vector<ll> a, ll e, size_t keep_length = 0, ll mod = NTT_MOD, ll root = NTT_ROOT) {
    vector<ll> result{1 % mod};
    while (e > 0) {
        if (e & 1) {
            result = multiply(result, a, mod, root);
            if (keep_length && result.size() > keep_length) result.resize(keep_length);
        }
        a = multiply(a, a, mod, root);
        if (keep_length && a.size() > keep_length) a.resize(keep_length);
        e >>= 1;
    }
    return result;
}

// Standard problem: two polynomials mod 998244353 - print the coefficients of their product
void solve() {
    int n, m;
    cin >> n >> m;
    vector<ll> a(n), b(m);
    for (ll &x : a) cin >> x;
    for (ll &x : b) cin >> x;
    vector<ll> c = multiply(a, b);
    for (size_t i = 0; i < c.size(); i++) cout << c[i] << " \n"[i + 1 == c.size()];
}
// ---------------- END VERBATIM COPY ----------------------------------------

// Driver only. multiply defaults to mod 998244353, which is this problem's modulus.
int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(nullptr);
    int n, m;
    cin >> n >> m;
    vector<ll> a(n), b(m);
    for (auto &x : a) cin >> x;
    for (auto &x : b) cin >> x;
    vector<ll> c = multiply(a, b);
    string out;
    for (size_t i = 0; i < c.size(); i++) out += to_string(c[i]) + (i + 1 < c.size() ? " " : "");
    cout << out << "\n";
}
