// ==========================================================================
// VERIFICATION SUBMISSION - Math/Number_Theory/Discrete_Log.cpp
//
// Target: https://judge.yosupo.jp/problem/discrete_logarithm_mod
//
// The block between the markers is the template copied byte for byte. Only the
// driver below it was added, to match this judge's input format.
// Generated by tools/verify.py - do not edit by hand.
// ==========================================================================

// ---------------- BEGIN VERBATIM COPY OF Math/Number_Theory/Discrete_Log.cpp ----------
// Discrete Log: the smallest x with a^x = b (mod m), by baby-step giant-step.
// Use when: "what power of a gives b modulo m", the order of an element, or the k-th x that satisfies the congruence.
// Handles: a and m NOT coprime, no solution at all (returns -1), and whether x = 0 counts as a solution.
// Time: O(sqrt(m) log m)
// Indexing: not applicable
// Note: x = 0 is only accepted when allow_zero is set, because problems differ on whether a^0 = 1 counts.

#include <bits/stdc++.h>
using namespace std;
using ll = long long;

ll pow_mod(ll base, ll exp, ll m) {
    ll res = 1 % m;
    base %= m;
    if (base < 0) base += m; // conditional, so a modulus near 9e18 cannot overflow
    while (exp > 0) {
        if (exp & 1) res = (ll)((__int128)res * base % m);
        base = (ll)((__int128)base * base % m);
        exp >>= 1;
    }
    return res;
}

// the smallest x >= 1 (or >= 0 when allow_zero) with a^x = b (mod m), or -1 if none exists
ll discrete_log(ll a, ll b, ll m, bool allow_zero = false) {
    if (m == 1) return allow_zero ? 0 : 1;
    a %= m;
    if (a < 0) a += m;
    b %= m;
    if (b < 0) b += m;
    if (allow_zero && 1 % m == b) return 0;

    ll n = (ll)sqrt((double)m) + 1, e = 1, f = 1, j = 1;
    unordered_map<ll, ll> seen;
    seen.reserve(n * 2);
    while (j <= n && (e = f = (ll)((__int128)e * a % m)) != b) {
        seen[(ll)((__int128)e * b % m)] = j++;
    }
    if (e == b) return j;
    if (__gcd(m, e) == __gcd(m, b))
        for (ll i = 2; i < n + 2; i++) {
            e = (ll)((__int128)e * f % m);
            auto it = seen.find(e);
            if (it != seen.end()) return n * i - it->second;
        }
    return -1;
}

// the gap between consecutive solutions, which is the multiplicative order of a; -1 when unsolvable
ll solution_period(ll a, ll b, ll m) {
    if (discrete_log(a, b, m) == -1) return -1;
    return discrete_log(a, 1, m);
}

ll kth_solution(ll a, ll b, ll m, ll k, bool allow_zero = false) { // the k-th smallest x, 1-based k
    ll first = discrete_log(a, b, m, allow_zero);
    if (first == -1) return -1;
    ll period = solution_period(a, b, m);
    if (period == -1) return -1;
    return first + (k - 1) * period;
}

// Standard problem: a, b and m - report the smallest x >= 1 with a^x = b (mod m), or -1
void solve() {
    ll a, b, m;
    cin >> a >> b >> m;
    cout << discrete_log(a, b, m) << '\n';
}
// ---------------- END VERBATIM COPY ----------------------------------------

// Driver only. The judge counts K = 0 as valid (it defines 0^0 = 1), which is what allow_zero enables.
int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(nullptr);
    int t;
    cin >> t;
    string out;
    while (t--) {
        ll x, y, m;
        cin >> x >> y >> m;
        out += to_string(discrete_log(x, y, m, true)) + "\n";
    }
    cout << out;
}
