// ==========================================================================
// VERIFICATION SUBMISSION - Math/Number_Theory/Miller_Rabin_Pollard_Rho.cpp
//
// Target: https://judge.yosupo.jp/problem/primality_test
//
// The block between the markers is the template copied byte for byte. Only the
// driver below it was added, to match this judge's input format.
// Generated by tools/verify.py - do not edit by hand.
// ==========================================================================

// ---------------- BEGIN VERBATIM COPY OF Math/Number_Theory/Miller_Rabin_Pollard_Rho.cpp ----------
// Miller Rabin Pollard Rho: primality and full factorization for numbers up to 9e18, far past trial division.
// Use when: "is this 18-digit number prime", factorizing one huge number, divisor counts of something near 1e18.
// Handles: n up to 9.2e18, n = 0 and 1, perfect powers, semiprimes of two large primes, and repeated factors.
// Time: is_prime O(log^3 n) | factorize about O(n^(1/4))
// Indexing: not applicable
// Note: is_prime is DETERMINISTIC for every 64-bit n with these bases, not probabilistic. Products use __int128.

#include <bits/stdc++.h>
using namespace std;
using ll = long long;
using ull = unsigned long long;

ull mul_mod(ull a, ull b, ull m) { return (__uint128_t)a * b % m; } // ll would overflow past ~3e9

ull pow_mod(ull b, ull e, ull m) {
    ull r = 1 % m;
    b %= m;
    while (e) {
        if (e & 1) r = mul_mod(r, b, m);
        b = mul_mod(b, b, m);
        e >>= 1;
    }
    return r;
}

// deterministic for all n < 3.3e24, so certainly for every unsigned 64-bit value
bool is_prime(ull n) {
    if (n < 2) return false;
    for (ull p : {2ULL, 3ULL, 5ULL, 7ULL, 11ULL, 13ULL, 17ULL, 19ULL, 23ULL, 29ULL, 31ULL, 37ULL}) {
        if (n % p == 0) return n == p;
    }
    ull d = n - 1;
    int s = 0;
    while ((d & 1) == 0) d >>= 1, s++;
    for (ull a : {2ULL, 3ULL, 5ULL, 7ULL, 11ULL, 13ULL, 17ULL, 19ULL, 23ULL, 29ULL, 31ULL, 37ULL}) {
        ull x = pow_mod(a, d, n);
        if (x == 1 || x == n - 1) continue;
        bool composite = true;
        for (int i = 1; i < s && composite; i++) {
            x = mul_mod(x, x, n);
            if (x == n - 1) composite = false;
        }
        if (composite) return false;
    }
    return true;
}

// one non-trivial divisor of a composite n, by Brent's variant of Pollard's rho
ull pollard_rho(ull n) {
    if (n % 2 == 0) return 2;
    static mt19937_64 rng(20260818);
    while (true) {
        ull x = rng() % n, c = rng() % n + 1, y = x, d = 1;
        auto step = [&](ull v) { return (mul_mod(v, v, n) + c) % n; };
        while (d == 1) {
            x = step(x);
            y = step(step(y));
            d = __gcd(x > y ? x - y : y - x, n);
        }
        if (d != n) return d; // d == n means this c failed, so pick another rather than give up
    }
}

// every prime factor with repetition, ascending
vector<ull> prime_factors(ull n) {
    if (n <= 1) return {};
    if (is_prime(n)) return {n};
    ull d = pollard_rho(n);
    vector<ull> left = prime_factors(d), right = prime_factors(n / d);
    left.insert(left.end(), right.begin(), right.end());
    sort(left.begin(), left.end());
    return left;
}

vector<pair<ull, int>> factorize(ull n) { // (prime, exponent), ascending
    vector<pair<ull, int>> out;
    for (ull p : prime_factors(n)) {
        if (!out.empty() && out.back().first == p) out.back().second++;
        else out.push_back({p, 1});
    }
    return out;
}

vector<ull> divisors(ull n) { // every divisor, ascending; there can be a lot of them
    vector<ull> divs{1};
    for (auto [p, e] : factorize(n)) {
        size_t was = divs.size();
        ull power = 1;
        for (int k = 1; k <= e; k++) {
            power *= p;
            for (size_t i = 0; i < was; i++) divs.push_back(divs[i] * power);
        }
    }
    sort(divs.begin(), divs.end());
    return divs;
}

// Standard problem: for each query n, report whether it is prime and its factorization
void solve() {
    int q;
    cin >> q;
    while (q--) {
        ull n;
        cin >> n;
        if (is_prime(n)) {
            cout << n << " PRIME\n";
            continue;
        }
        for (auto [p, e] : factorize(n)) cout << p << '^' << e << ' ';
        cout << '\n';
    }
}
// ---------------- END VERBATIM COPY ----------------------------------------

// Driver only.
int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(nullptr);
    int q;
    cin >> q;
    string out;
    while (q--) {
        unsigned long long n;
        cin >> n;
        out += is_prime(n) ? "Yes\n" : "No\n";
    }
    cout << out;
}
