// ==========================================================================
// VERIFICATION SUBMISSION - Strings/Z_Function.cpp
//
// Target: https://judge.yosupo.jp/problem/zalgorithm
//
// The block between the markers is the template copied byte for byte. Only the
// driver below it was added, to match this judge's input format.
// Generated by tools/verify.py - do not edit by hand.
// ==========================================================================

// ---------------- BEGIN VERBATIM COPY OF Strings/Z_Function.cpp ----------
// Z Algorithm: for every position, the length of the longest prefix of the string that starts there.
// Use when: "find all occurrences of p in s", longest common prefix of the string with each of its suffixes, periods.
// Handles: z array of any string, all matches of a pattern, any alphabet. z[0] is left at 0.
// Time: build O(n) | match O(n + m)
// Indexing: 0-based; match() returns 0-based start positions in the text
// Note: match() builds z over pattern + '#' + text, so '#' must not appear in either string.

#include <bits/stdc++.h>
using namespace std;
#define sz(x) (int)(x).size()

struct Zfunctions {
    vector<int> z;

    void build(const string &s) { // fills z over s
        int n = sz(s);
        z.assign(n, 0);
        for (int i = 1, l = 0, r = 0; i < n; i++) {
            if (i <= r) z[i] = min(r - i + 1, z[i - l]);
            while (i + z[i] < n && s[z[i]] == s[i + z[i]]) z[i]++;
            if (i + z[i] - 1 > r) l = i, r = i + z[i] - 1;
        }
    }

    int operator[](int i) { return z[i]; }

    vector<int> match(const string &s, const string &pattern) { // 0-based positions of pattern inside s
        vector<int> ans;
        string t = pattern + "#" + s;
        build(t);
        for (int i = sz(pattern) + 1; i < sz(t); i++)
            if (z[i] >= sz(pattern)) ans.push_back(i - sz(pattern) - 1);
        return ans;
    }
};

// Standard problem: print the z array of s, then every 0-based occurrence of p in s
void solve() {
    string s, p;
    cin >> s >> p;
    Zfunctions z;
    z.build(s);
    for (int i = 0; i < sz(s); i++) cout << z[i] << ' ';
    cout << '\n';
    for (int i : z.match(s, p)) cout << i << ' ';
    cout << '\n';
}
// ---------------- END VERBATIM COPY ----------------------------------------

// Driver only. The judge wants a_0 = |S|; build() leaves z[0] = 0 by convention, so the driver prints it.
int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(nullptr);
    string s;
    cin >> s;
    Zfunctions z;
    z.build(s);
    string out = to_string(s.size());
    for (size_t i = 1; i < s.size(); i++) out += " " + to_string(z[(int)i]);
    cout << out << "\n";
}
