// ==========================================================================
// VERIFICATION SUBMISSION - DP/Longest_Increasing_Subsequence.cpp
//
// Target: https://judge.yosupo.jp/problem/longest_increasing_subsequence
//
// The block between the markers is the template copied byte for byte. Only the
// driver below it was added, to match this judge's input format.
// Generated by tools/verify.py - do not edit by hand.
// ==========================================================================

// ---------------- BEGIN VERBATIM COPY OF DP/Longest_Increasing_Subsequence.cpp ----------
// Longest Increasing Subsequence: the longest run of indices whose values increase, with the subsequence itself.
// Use when: "longest increasing subsequence", minimum removals to sort, patience sorting, Dilworth-style chain covers.
// Handles: strictly increasing or non-decreasing, duplicates, negatives, the empty array, and reconstruction.
// Time: O(n log n)
// Indexing: 0-based array; the reconstruction returns the values, and indices_of returns their positions
// Note: strict uses lower_bound and non-decreasing uses upper_bound - the same call for both is the usual bug here.

#include <bits/stdc++.h>
using namespace std;

// length only
template <typename T> int lis_length(const vector<T> &a, bool strict = true) {
    vector<T> tail; // tail[k] = smallest possible last value of an increasing run of length k+1
    for (const T &x : a) {
        auto it = strict ? lower_bound(tail.begin(), tail.end(), x) : upper_bound(tail.begin(), tail.end(), x);
        if (it == tail.end())
            tail.push_back(x);
        else
            *it = x;
    }
    return (int)tail.size();
}

// the positions of one longest increasing subsequence, ascending
template <typename T> vector<int> lis_indices(const vector<T> &a, bool strict = true) {
    int n = (int)a.size();
    if (n == 0) return {};
    vector<T> tail;
    vector<int> tail_index, parent(n, -1);
    for (int i = 0; i < n; i++) {
        auto it = strict ? lower_bound(tail.begin(), tail.end(), a[i]) : upper_bound(tail.begin(), tail.end(), a[i]);
        int k = (int)(it - tail.begin());
        if (k > 0) parent[i] = tail_index[k - 1]; // whoever ends the run one shorter
        if (it == tail.end())
            tail.push_back(a[i]), tail_index.push_back(i);
        else
            tail[k] = a[i], tail_index[k] = i;
    }
    vector<int> out;
    for (int i = tail_index.back(); i != -1; i = parent[i]) out.push_back(i);
    reverse(out.begin(), out.end());
    return out;
}

template <typename T> vector<T> lis_values(const vector<T> &a, bool strict = true) {
    vector<T> out;
    for (int i : lis_indices(a, strict)) out.push_back(a[i]);
    return out;
}

// the longest DEcreasing subsequence, by running the same thing on the reversed sign
template <typename T> int lds_length(const vector<T> &a, bool strict = true) {
    vector<T> flipped;
    for (const T &x : a) flipped.push_back(-x);
    return lis_length(flipped, strict);
}

// Standard problem: report the length of the longest strictly increasing subsequence, then the subsequence
void solve() {
    int n;
    cin >> n;
    vector<int> a(n);
    for (int &x : a) cin >> x;
    vector<int> idx = lis_indices(a);
    cout << idx.size() << '\n';
    for (size_t i = 0; i < idx.size(); i++) cout << a[idx[i]] << " \n"[i + 1 == idx.size()];
}
// ---------------- END VERBATIM COPY ----------------------------------------

// Driver only. The judge wants the INDICES of a longest strictly increasing subsequence.
int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(nullptr);
    int n;
    cin >> n;
    vector<int> a(n);
    for (auto &x : a) cin >> x;
    vector<int> idx = lis_indices(a, true);
    string out = to_string(idx.size()) + "\n";
    for (size_t i = 0; i < idx.size(); i++) out += to_string(idx[i]) + (i + 1 < idx.size() ? " " : "");
    cout << out << "\n";
}
