// ==========================================================================
// VERIFICATION SUBMISSION - Range_Query/Wavelet_Tree.cpp
//
// Target: https://judge.yosupo.jp/problem/range_kth_smallest
//
// The block between the markers is the template copied byte for byte. Only the
// driver below it was added, to match this judge's input format.
// Generated by tools/verify.py - do not edit by hand.
// ==========================================================================

// ---------------- BEGIN VERBATIM COPY OF Range_Query/Wavelet_Tree.cpp ----------
// Wavelet Tree: k-th smallest, rank, frequency and conditional sum over a range of a static array.
// Use when: "k-th smallest in [l, r]", "how many in [l, r] are <= k", "sum of elements <= k in [l, r]".
// Handles: negative values, duplicates, any value range passed to init(). Static - no updates.
// Time: build O(n log V) | kth / LTE / count / sum O(log V), V = hi - lo
// Indexing: 1-based over the array; init() takes pointers to a[1] and a[n+1]
// Note: init() permutes the input array - copy it first if you still need the original order.

#include <bits/stdc++.h>
using namespace std;
using ll = long long;

const int MAXN = (int)3e5 + 9;
const int MAXV = (int)1e9 + 9;

struct wavelet_tree {
    int lo, hi;
    wavelet_tree *l, *r;
    int *b, bsz;
    ll *c;
    int csz; // c holds prefix sums, widened so sums cannot overflow

    wavelet_tree() {
        lo = 1;
        hi = 0;
        bsz = 0;
        csz = 0, l = NULL;
        r = NULL;
    }

    void init(int *from, int *to, int x, int y) {
        lo = x, hi = y;
        if (from >= to) return;
        int mid = (lo + hi) >> 1;
        auto f = [mid](int x) { return x <= mid; };
        b = (int *)malloc((to - from + 2) * sizeof(int));
        bsz = 0;
        b[bsz++] = 0;
        c = (ll *)malloc((to - from + 2) * sizeof(ll));
        csz = 0;
        c[csz++] = 0;
        for (auto it = from; it != to; it++) {
            b[bsz] = (b[bsz - 1] + f(*it));
            c[csz] = (c[csz - 1] + (*it));
            bsz++;
            csz++;
        }
        if (hi == lo) return;
        auto pivot = stable_partition(from, to, f);
        l = new wavelet_tree();
        l->init(from, pivot, lo, mid);
        r = new wavelet_tree();
        r->init(pivot, to, mid + 1, hi);
    }

    int kth(int l, int r, int k) { // k-th smallest of a[l .. r], k is 1-based
        if (l > r) return 0;
        if (lo == hi) return lo;
        int inLeft = b[r] - b[l - 1], lb = b[l - 1], rb = b[r];
        if (k <= inLeft) return this->l->kth(lb + 1, rb, k);
        return this->r->kth(l - lb, r - rb, k - inLeft);
    }

    int LTE(int l, int r, int k) { // how many of a[l .. r] are <= k
        if (l > r || k < lo) return 0;
        if (hi <= k) return r - l + 1;
        int lb = b[l - 1], rb = b[r];
        return this->l->LTE(lb + 1, rb, k) + this->r->LTE(l - lb, r - rb, k);
    }

    int count(int l, int r, int k) { // how many of a[l .. r] equal k
        if (l > r || k < lo || k > hi) return 0;
        if (lo == hi) return r - l + 1;
        int lb = b[l - 1], rb = b[r];
        int mid = (lo + hi) >> 1;
        if (k <= mid) return this->l->count(lb + 1, rb, k);
        return this->r->count(l - lb, r - rb, k);
    }

    ll sum(int l, int r, int k) { // sum of those of a[l .. r] that are <= k
        if (l > r or k < lo) return 0;
        if (hi <= k) return c[r] - c[l - 1];
        int lb = b[l - 1], rb = b[r];
        return this->l->sum(lb + 1, rb, k) + this->r->sum(l - lb, r - rb, k);
    }

    ~wavelet_tree() {
        delete l;
        delete r;
    }
};

wavelet_tree t;
int a[MAXN];

// Standard problem: type 0 k-th smallest, 1 count <= k, 2 count == k, 3 sum of those <= k, all on [l, r]
void solve() {
    int n, q, l, r, k;
    cin >> n;
    for (int i = 1; i <= n; i++) cin >> a[i];
    t.init(a + 1, a + n + 1, -MAXV, MAXV);
    cin >> q;
    while (q--) {
        int type;
        cin >> type >> l >> r >> k;
        if (type == 0)
            cout << t.kth(l, r, k) << '\n';
        else if (type == 1)
            cout << t.LTE(l, r, k) << '\n';
        else if (type == 2)
            cout << t.count(l, r, k) << '\n';
        else
            cout << t.sum(l, r, k) << '\n';
    }
}
// ---------------- END VERBATIM COPY ----------------------------------------

// Driver only. kth(l, r, k) is 1-based inclusive with k 1-based; the judge is 0-based, [l, r), k 0-based.
int main() {
    ios_base::sync_with_stdio(false);
    cin.tie(nullptr);
    int n, q;
    cin >> n >> q;
    for (int i = 1; i <= n; i++) cin >> a[i];
    t.init(a + 1, a + n + 1, -MAXV, MAXV);
    string out;
    while (q--) {
        int l, r, k;
        cin >> l >> r >> k;
        out += to_string(t.kth(l + 1, r, k + 1)) + "\n";
    }
    cout << out;
}
