#!/usr/bin/env python3
"""End-to-end verification against real judge test data.

For each entry in verify/manifest.tsv:
  1. concatenate the template BYTE FOR BYTE with its driver (which holds only main())
  2. download the judge's full system tests, cached under verify/.cache/
  3. compile and run every case, comparing against the judge's expected output

Nothing here edits a template. If a template and its generated submission ever differ,
that is a bug in this script, and verify/check_verbatim.py will say so.
"""
import argparse, json, os, pathlib, re, shutil, subprocess, sys, time

ROOT = pathlib.Path(__file__).resolve().parent.parent
VERIFY = ROOT / 'verify'
CACHE = VERIFY / '.cache'
BUILD = VERIFY / '.build'
BEGIN = '// ---------------- BEGIN VERBATIM COPY OF '
END = '// ---------------- END VERBATIM COPY ----------------------------------------'


def entries(only=None):
    out = []
    for line in (VERIFY / 'manifest.tsv').read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        name, template, url = line.split('\t')[:3]
        if only and only.lower() not in name.lower():
            continue
        out.append((name, template, url))
    return out


def generate(name, template, url):
    """Build verify/<name>/main.cpp = banner + template verbatim + driver."""
    src = (ROOT / template).read_text(encoding='utf-8')
    driver = (VERIFY / 'drivers' / (name + '.cpp')).read_text(encoding='utf-8')
    out = VERIFY / name
    out.mkdir(parents=True, exist_ok=True)
    text = (
        '// ' + '=' * 74 + '\n'
        '// VERIFICATION SUBMISSION - ' + template + '\n'
        '//\n'
        '// Target: ' + url + '\n'
        '//\n'
        '// The block between the markers is the template copied byte for byte. Only the\n'
        '// driver below it was added, to match this judge\'s input format.\n'
        '// Generated by tools/verify.py - do not edit by hand.\n'
        '// ' + '=' * 74 + '\n\n'
        + BEGIN + template + ' ' + '-' * 10 + '\n'
        + src
        + END + '\n\n'
        + driver
    )
    (out / 'main.cpp').write_text(text, encoding='utf-8', newline='\n')
    return out / 'main.cpp'


def fetch_tests(url):
    slug = url.rstrip('/').split('/')[-1]
    d = CACHE / slug
    if d.exists() and any(d.glob('*.in')):
        return d, False
    d.mkdir(parents=True, exist_ok=True)
    r = subprocess.run(['oj', 'd', '--system', '-d', str(d), url],
                       capture_output=True, text=True, timeout=1800)
    if not any(d.glob('*.in')):
        sys.stderr.write(r.stdout[-2000:] + r.stderr[-2000:])
        shutil.rmtree(d, ignore_errors=True)
        raise RuntimeError('no test data downloaded for ' + url)
    return d, True


PATHS = {}


def problem_path(slug):
    """category/name inside library-checker-problems, for fetching checker.cpp and info.toml."""
    if not PATHS:
        import json, urllib.request
        cache = CACHE / 'index.json'
        if cache.exists():
            PATHS.update(json.loads(cache.read_text()))
        else:
            u = 'https://api.github.com/repos/yosupo06/library-checker-problems/git/trees/master?recursive=1'
            tree = json.load(urllib.request.urlopen(u, timeout=60))['tree']
            for e in tree:
                if e['path'].count('/') == 2 and e['path'].endswith('/info.toml'):
                    cat, name, _ = e['path'].split('/')
                    PATHS[name] = cat + '/' + name
            CACHE.mkdir(parents=True, exist_ok=True)
            cache.write_text(json.dumps(PATHS))
    return PATHS.get(slug)


def judge_assets(slug):
    """(checker exe or None, time limit). A checker means the problem accepts any valid answer."""
    import urllib.request, urllib.error
    d = CACHE / slug
    path = problem_path(slug)
    if not path:
        return None, 10.0
    raw = 'https://raw.githubusercontent.com/yosupo06/library-checker-problems/master/'
    limit = 10.0
    info = d / 'info.toml'
    if not info.exists():
        try:
            info.write_bytes(urllib.request.urlopen(raw + path + '/info.toml', timeout=60).read())
        except Exception:
            pass
    if info.exists():
        m = re.search(r'timelimit\s*=\s*([0-9.]+)', info.read_text(encoding='utf-8', errors='replace'))
        if m:
            limit = float(m.group(1))
    exe = d / 'checker.exe'
    if exe.exists():
        return exe, limit
    src, tl = d / 'checker.cpp', d / 'testlib.h'
    if not src.exists():
        try:
            src.write_bytes(urllib.request.urlopen(raw + path + '/checker.cpp', timeout=60).read())
        except urllib.error.HTTPError:
            return None, limit
        except Exception:
            return None, limit
    if not tl.exists():
        tl.write_bytes(urllib.request.urlopen(raw + 'common/testlib.h', timeout=120).read())
    r = subprocess.run(['g++', '-std=c++17', '-O2', '-w', '-I', str(d), '-o', str(exe), str(src)],
                       capture_output=True, text=True)
    return (exe if exe.exists() else None), limit


def run_one(name, template, url, tle):
    cpp = generate(name, template, url)
    BUILD.mkdir(parents=True, exist_ok=True)
    exe = BUILD / (name + '.exe')
    # -Wl,--stack matches what real judges give; Windows defaults to ~1 MB and would
    # report a stack overflow for recursion depths that pass everywhere else.
    c = subprocess.run(['g++', '-std=c++17', '-O2', '-Wall', '-Wl,--stack,268435456', '-o', str(exe), str(cpp)],
                       capture_output=True, text=True)
    if c.returncode != 0:
        return dict(name=name, status='CE', detail=c.stderr.strip().splitlines()[:6], cases=0, slowest=0)
    tests, _ = fetch_tests(url)
    slug = url.rstrip('/').split('/')[-1]
    checker, limit = judge_assets(slug)
    tle = max(tle, limit * 3)  # this machine is not the judge; allow headroom over the stated limit
    total = passed = 0
    slowest = 0.0
    failures = []
    for inp in sorted(tests.glob('*.in')):
        exp = inp.with_suffix('.out')
        if not exp.exists():
            continue
        total += 1
        t0 = time.time()
        try:
            p = subprocess.run([str(exe)], stdin=inp.open('rb'), capture_output=True, timeout=tle)
        except subprocess.TimeoutExpired:
            failures.append((inp.name, 'TLE'))
            slowest = max(slowest, tle)
            continue
        dt = time.time() - t0
        slowest = max(slowest, dt)
        if p.returncode != 0:
            failures.append((inp.name, 'RE rc=%d' % p.returncode))
            continue
        if checker:  # the judge's own checker: these problems accept any valid answer
            mine = BUILD / (name + '.myout')
            mine.write_bytes(p.stdout)
            v = subprocess.run([str(checker), str(inp), str(mine), str(exp)], capture_output=True)
            if v.returncode == 0:
                passed += 1
            else:
                failures.append((inp.name, 'WA ' + v.stderr.decode('utf-8', 'replace').strip()[:60]))
        elif p.stdout.decode('utf-8', 'replace').split() == exp.read_text(encoding='utf-8', errors='replace').split():
            passed += 1
        else:
            failures.append((inp.name, 'WA'))
    status = 'AC' if total and passed == total else ('WA' if total else 'NO-TESTS')
    if failures and all(f[1] == 'TLE' for f in failures):
        status = 'TLE'
    return dict(name=name, status=status, cases=total, passed=passed,
                slowest=slowest, limit=limit, detail=failures[:5])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--only', help='substring of the template name')
    ap.add_argument('--tle', type=float, default=10.0, help='seconds per case')
    a = ap.parse_args()
    rows = entries(a.only)
    width = max((len(r[0]) for r in rows), default=10)
    bad = 0
    results = {}
    store = VERIFY / 'results.json'
    if store.exists():
        results = json.loads(store.read_text(encoding='utf-8'))
    for name, template, url in rows:
        try:
            r = run_one(name, template, url, a.tle)
        except Exception as e:
            r = dict(name=name, status='ERROR', cases=0, passed=0, slowest=0, limit=0, detail=[str(e)[:200]])
        mark = {'AC': 'AC  '}.get(r['status'], r['status'].ljust(4))
        print('%s  %-*s  %2d/%-2d cases  %5.2fs  %s' % (
            mark, width, name, r.get('passed', 0), r['cases'], r['slowest'],
            '' if r['status'] == 'AC' else str(r['detail'])[:110]), flush=True)
        results[name] = dict(template=template, url=url, status=r['status'],
                             cases=r['cases'], passed=r.get('passed', 0), slowest=round(r['slowest'], 2),
                             limit=r.get('limit', 0))
        store.write_text(json.dumps(results, indent=1, sort_keys=True), encoding='utf-8')
        if r['status'] != 'AC':
            bad += 1
    print('\n%d verified | %d not' % (len(rows) - bad, bad))
    return 1 if bad else 0


if __name__ == '__main__':
    sys.exit(main())
